cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ASIAQF3LPAFDA5IK4K5A
      secret-key: RdX95LfdwQfDIbFnvlgIV4Y7n7CsjvXrRyvlyiqK
      session-token: FwoGZXIvYXdzEHoaDK/NP1D/OV9JEZ7m+SLUAWy3d/8ZomsN6sKLMjFb01qFo9BmyNlTEbQr1gAzJFL36aJf/mL5cFuqx2mC17En45KBg6pWFmdbUD9F0dGe8YgRgd466JEgTEeO6WbMbJT3h8nlK00DpWmMvNq0xhM0Ce+qiGRGx1o2ebDJv8KqDX77JZ171mm6OYK7/IqN0NVJxLDYY6tUpKzsa9gEL9E3pS14izQL75ymzh15j84M+e/5flHZYL6XY50M1BB9dxh0/Wqq3UxStrD/EbNYSbMVkRFaEFn8a6icomOAbOCaR7jVl2pDKMrftowGMi2o8RB/zUQ6oy8kTYRGHypc684pUcOgdy2JXAQmJCaPlW2rler/LKo8ebYn9f0=
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/012573409606/cola2
